# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/alexnet
# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/densenet100bc
# CUDA_VISIBLE_DEVICES=0,1 python train.py --work_path ./experiments/cifar10/2_cnns/densenet190bc
# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/lenet
# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/preresnet110
# CUDA_VISIBLE_DEVICES=0,1 python train.py --work_path ./experiments/cifar10/2_cnns/preresnet1202
# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/preresnet20
CUDA_VISIBLE_DEVICES=0,1 python train.py --work_path ./experiments/cifar10/2_cnns/resnext29_16x64d
CUDA_VISIBLE_DEVICES=0,1 python train.py --work_path ./experiments/cifar10/2_cnns/se_resnext29_16x64d
CUDA_VISIBLE_DEVICES=0,1 python train.py --work_path ./experiments/cifar10/2_cnns/shake_resnet26_2x64d
# CUDA_VISIBLE_DEVICES=0 python train.py --work_path ./experiments/cifar10/2_cnns/vgg19
